#서버 포트
server : 
  port : 8000

# 스프링프레임워크 로그 출력
#logging :
#  level : 
#    org.springframework : DEBUG

spring : 
  messages:    basename: messages

    
# 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 

     