#서버 포트
server : 
  port : 8000

# 스프링프레임워크 로그 출력
#logging :
#  level : 
#    org.springframework : DEBUG

spring : 
  messages:
    basename: messages
#  security : 
#    user :
#      name : username
#      password : qweasd 
  h2:
    console:
      enabled: true
  jpa : 
   show-sql : true
  datasource:
    url: jdbc:h2:mem:testdb  

    
# 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 

     